---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install python3
  become: yes
  apt:
    name: python3


- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/web
    state: directory

- name: Copy index test page
  copy:
    src: "/home/circleci/project/artifact.tar.gz"
    dest: "/home/ubuntu/web/artifact.tar.gz"

- name: Extract 
  ansible.builtin.unarchive:
    src: "/home/ubuntu/web/artifact.tar.gz"
    dest: "/home/ubuntu/web/"

- name: task name
  shell:
    command: /home/ubuntu/web npm install

- name: task name
  shell:
    command: /home/ubuntu/web pm2 stop default

- name: task name
  shell:
    command: /home/ubuntu/web pm2 start npm -- start
